// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq4gxpyd1qNiI-eY-SWdSVPlvtwtqw7wM',
    appId: '1:699900939200:web:5b88b39736e38129eb1625',
    messagingSenderId: '699900939200',
    projectId: 'kala-krithi',
    authDomain: 'kala-krithi.firebaseapp.com',
    storageBucket: 'kala-krithi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxY7zHICDaAR81Ja6opb7mN0PwOOiuL7Q',
    appId: '1:699900939200:android:1e600b9df9164213eb1625',
    messagingSenderId: '699900939200',
    projectId: 'kala-krithi',
    storageBucket: 'kala-krithi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvyFUIo8Iba7FRF2Nizf8NnRDwjFaVQ4A',
    appId: '1:699900939200:ios:abedeb05d9dea3bfeb1625',
    messagingSenderId: '699900939200',
    projectId: 'kala-krithi',
    storageBucket: 'kala-krithi.firebasestorage.app',
    iosBundleId: 'com.example.kalkrithi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvyFUIo8Iba7FRF2Nizf8NnRDwjFaVQ4A',
    appId: '1:699900939200:ios:abedeb05d9dea3bfeb1625',
    messagingSenderId: '699900939200',
    projectId: 'kala-krithi',
    storageBucket: 'kala-krithi.firebasestorage.app',
    iosBundleId: 'com.example.kalkrithi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq4gxpyd1qNiI-eY-SWdSVPlvtwtqw7wM',
    appId: '1:699900939200:web:73d079ea879f3d22eb1625',
    messagingSenderId: '699900939200',
    projectId: 'kala-krithi',
    authDomain: 'kala-krithi.firebaseapp.com',
    storageBucket: 'kala-krithi.firebasestorage.app',
  );
}
